"""Real public evidence records for the MVP vertical slice.

This file is still a curated seed set, but the records below are based on
publicly reachable source pages instead of synthetic placeholders. The next
step is automating ingestion from the same source classes.
"""

from __future__ import annotations

from datetime import date

from .models import Claim, Document, Technology


TECHNOLOGIES = [
    Technology("tech_gpu", "GPU", "Compute", ("accelerator", "AI accelerator", "Blackwell", "Rubin")),
    Technology("tech_hbm", "HBM", "Memory", ("high bandwidth memory", "HBM3E", "HBM4")),
    Technology("tech_cowos", "CoWoS", "Packaging", ("advanced packaging", "interposer", "2.5D packaging")),
    Technology("tech_networking", "Networking", "Networking", ("ethernet", "infiniband", "switching")),
    Technology("tech_switch_asic", "Switch ASIC", "Networking", ("Tomahawk", "Spectrum-X", "Jericho")),
    Technology("tech_optical_transceiver", "Optical Transceiver", "Optical", ("800G", "1.6T", "pluggable optics")),
    Technology("tech_cpo", "CPO", "Optical", ("co-packaged optics", "silicon photonics")),
    Technology("tech_power", "Power", "Power", ("grid", "substation", "interconnect", "electricity")),
    Technology("tech_transformer", "Transformer", "Power", ("large power transformer", "LPT")),
    Technology("tech_cooling", "Cooling", "Cooling", ("liquid cooling", "thermal", "CDU", "chiller")),
    Technology("tech_rack_density", "Rack Density", "Data Center", ("rack-scale", "rack density", "NVL72")),
]


DOCUMENTS = [
    Document(
        "doc_iea_power_2026",
        "Data centre electricity use surged in 2025",
        "IEA",
        "research_report",
        date(2026, 5, 1),
        "https://www.iea.org/news/data-centre-electricity-use-surged-in-2025-even-with-tightening-bottlenecks-driving-a-scramble-for-solutions",
        "IEA reported that data-center electricity demand grew sharply in 2025, with AI-focused data centers growing faster than the wider electricity system.",
        0.96,
    ),
    Document(
        "doc_bloom_power_2026",
        "2026 Data Center Power Report",
        "Bloom Energy",
        "industry_report",
        date(2026, 1, 1),
        "https://www.bloomenergy.com/wp-content/uploads/2026-power-report.pdf",
        "Bloom Energy described widening interconnection timelines and uncertainty as AI data-center demand outpaced grid delivery at scale.",
        0.78,
    ),
    Document(
        "doc_nvidia_800v_power",
        "NVIDIA 800 VDC Architecture Will Power the Next Generation of AI Factories",
        "NVIDIA",
        "technical_blog",
        date(2025, 5, 19),
        "https://developer.nvidia.com/blog/nvidia-800-v-hvdc-architecture-will-power-the-next-generation-of-ai-factories/",
        "NVIDIA described an 800 VDC transition for AI factories to support one-megawatt IT racks and beyond from 2027.",
        0.9,
    ),
    Document(
        "doc_dwarkesh_dylan_2026",
        "Dylan Patel deep dive on bottlenecks to scaling AI compute",
        "Dwarkesh Podcast / Dylan Patel",
        "interview_transcript",
        date(2026, 3, 13),
        "https://www.dwarkesh.com/p/dylan-patel",
        "Dylan Patel discussed bottlenecks to scaling AI compute, including logic, memory, power, networking, cooling, and rack integration.",
        0.86,
    ),
    Document(
        "doc_nvidia_blackwell_cooling",
        "NVIDIA Blackwell Platform Boosts Water Efficiency by Over 300x",
        "NVIDIA",
        "technical_blog",
        date(2025, 4, 1),
        "https://blogs.nvidia.com/blog/blackwell-platform-water-efficiency-liquid-cooling-data-centers-ai-factories/",
        "NVIDIA presented GB200 NVL72 as a rack-scale liquid-cooled system designed for high compute density, energy cost, and heat constraints.",
        0.9,
    ),
    Document(
        "doc_nvidia_mgx_density",
        "Building the Modular Foundation for AI Factories with NVIDIA MGX",
        "NVIDIA",
        "technical_blog",
        date(2025, 4, 15),
        "https://developer.nvidia.com/blog/building-the-modular-foundation-for-ai-factories-with-nvidia-mgx/",
        "NVIDIA said modern AI compute requirements drive higher power density and liquid-cooled infrastructure, with Blackwell racks reaching high power levels.",
        0.9,
    ),
    Document(
        "doc_afcom_density",
        "The Data Center Density Dilemma",
        "AFCOM",
        "industry_article",
        date(2026, 3, 1),
        "https://afcom.com/news/720658/The-Data-Center-Density-Dilemma.htm",
        "AFCOM described average rack density rising and liquid cooling adoption accelerating as AI deployment becomes foundational.",
        0.76,
    ),
    Document(
        "doc_micron_q2_2026",
        "Micron Fiscal Q2 2026 Earnings Call Prepared Remarks",
        "Micron",
        "earnings_transcript",
        date(2026, 3, 18),
        "https://investors.micron.com/static-files/e089f8c0-065d-47b8-9d02-bfa863cdb357",
        "Micron said AI server demand remains strong and both AI and traditional server demand are constrained by inadequate DRAM and NAND supply.",
        0.9,
    ),
    Document(
        "doc_micron_hbm4_2026",
        "Micron in High-Volume Production of HBM4 Designed for NVIDIA Vera Rubin",
        "Micron",
        "press_release",
        date(2026, 3, 16),
        "https://investors.micron.com/news-releases/news-release-details/micron-high-volume-production-hbm4-designed-nvidia-vera-rubin",
        "Micron announced volume shipments of HBM4 designed for NVIDIA Vera Rubin, showing capacity ramp progress and platform alignment.",
        0.88,
    ),
    Document(
        "doc_skhynix_outlook_2026",
        "2026 Market Outlook: SK hynix's HBM to Fuel AI Memory Boom",
        "SK Hynix",
        "company_article",
        date(2026, 1, 1),
        "https://news.skhynix.com/2026-market-outlook-focus-on-the-hbm-led-memory-supercycle/",
        "SK hynix described rapid growth expectations for AI-specific memory with HBM at the center from 2025 to 2028.",
        0.86,
    ),
    Document(
        "doc_tsmc_cowos_2026",
        "TSMC Debuts A13 Technology at 2026 North America Technology Symposium",
        "TSMC",
        "press_release",
        date(2026, 5, 1),
        "https://pr.tsmc.com/english/news/3302",
        "TSMC said it continues expanding CoWoS to support AI demand for more computing power and memory in a single package.",
        0.9,
    ),
    Document(
        "doc_arista_ai_networking",
        "AI Networking Whitepaper",
        "Arista",
        "whitepaper",
        date(2026, 6, 10),
        "https://www.arista.com/assets/data/pdf/Whitepapers/AI-Network-WP.pdf",
        "Arista described very large Ethernet AI clusters and noted design, space, and power-consumption challenges at that scale.",
        0.84,
    ),
    Document(
        "doc_nvidia_spectrumx",
        "NVIDIA Spectrum-X Ethernet Platform for AI Networking",
        "NVIDIA",
        "product_page",
        date(2026, 1, 6),
        "https://www.nvidia.com/en-us/networking/spectrumx/",
        "NVIDIA presents Spectrum-X as an AI networking platform for scaling within and across data centers, including photonics for power efficiency.",
        0.86,
    ),
    Document(
        "doc_broadcom_ai_networking",
        "Broadcom Delivers End-to-End AI Networking",
        "Broadcom",
        "press_release",
        date(2025, 10, 1),
        "https://investors.broadcom.com/news-releases/news-release-details/broadcom-delivers-future-ai-infrastructure-end-end-ai-networking",
        "Broadcom described Tomahawk, Jericho, and CPO switching as an open, scalable, power-efficient AI networking platform.",
        0.84,
    ),
    Document(
        "doc_broadcom_cpo_reliability",
        "Broadcom Showcases Quality and Reliability of Co-Packaged Optics",
        "Broadcom",
        "press_release",
        date(2025, 10, 1),
        "https://www.broadcom.com/company/news/product-releases/63616",
        "Broadcom reported that CPO can reduce optics power versus pluggable module approaches and improve link reliability.",
        0.84,
    ),
    Document(
        "doc_nvidia_cpo",
        "Scaling AI Factories with Co-Packaged Optics",
        "NVIDIA",
        "technical_blog",
        date(2025, 9, 1),
        "https://developer.nvidia.com/blog/scaling-ai-factories-with-co-packaged-optics-for-better-power-efficiency/",
        "NVIDIA described co-packaged optics for better power efficiency, with commercial availability planned across 2026 switch platforms.",
        0.88,
    ),
    Document(
        "doc_coherent_cpo_lasers",
        "Coherent OFC 2026 Investor Event Deck",
        "Coherent",
        "investor_presentation",
        date(2026, 3, 17),
        "https://www.coherent.com/content/dam/coherent/site/en/documents/investors/investor-presentations/2026/march-17/OFC-2026-Investor%20event-deck-vf.pdf",
        "Coherent said it is producing high-power lasers in volume for silicon photonic transceivers and CPO solutions.",
        0.82,
    ),
    Document(
        "doc_lumentum_pluggables",
        "Data Center Products",
        "Lumentum",
        "product_page",
        date(2026, 2, 10),
        "https://www.lumentum.com/en/products/data-center",
        "Lumentum describes scalable optical technologies including 800G and 1.6T modules plus future ELSFP modules for CPO architectures.",
        0.8,
    ),
]


CLAIMS = [
    Claim(
        "claim_power_iea_demand",
        "doc_iea_power_2026",
        "tech_power",
        "demand_signal",
        "AI data-center electricity demand is growing faster than the broader power system.",
        "Data-center electricity demand grew sharply in 2025, with AI-focused sites growing faster.",
        0.9,
        94,
    ),
    Claim(
        "claim_power_bloom_infra",
        "doc_bloom_power_2026",
        "tech_power",
        "infrastructure_constraint",
        "Grid interconnection timelines and delivery uncertainty are constraining AI data-center buildout.",
        "Interconnection timelines and uncertainty widened as demand outpaced grid delivery.",
        0.78,
        90,
    ),
    Claim(
        "claim_power_nvidia_technical",
        "doc_nvidia_800v_power",
        "tech_power",
        "technical_constraint",
        "The move toward one-megawatt racks requires a major power-distribution architecture transition.",
        "NVIDIA described 800 VDC architecture for one-megawatt IT racks and beyond.",
        0.86,
        88,
    ),
    Claim(
        "claim_power_dylan_counter",
        "doc_dwarkesh_dylan_2026",
        "tech_power",
        "counterargument",
        "Power may be partly mitigated through integrated rack design, fewer field connections, and build-process improvements.",
        "Dylan Patel discussed integrated racks reducing cabling, power connections, and plumbing work.",
        0.74,
        48,
    ),
    Claim(
        "claim_cooling_nvidia_demand",
        "doc_nvidia_blackwell_cooling",
        "tech_cooling",
        "demand_signal",
        "Blackwell-class rack-scale systems push thermal and energy constraints toward liquid cooling.",
        "GB200 NVL72 is a rack-scale liquid-cooled system for high density and heat constraints.",
        0.88,
        88,
    ),
    Claim(
        "claim_cooling_mgx_technical",
        "doc_nvidia_mgx_density",
        "tech_cooling",
        "technical_constraint",
        "Rising AI rack power density is driving liquid-cooled infrastructure requirements.",
        "Modern AI compute requirements drive higher power density and liquid-cooled infrastructure.",
        0.86,
        87,
    ),
    Claim(
        "claim_cooling_afcom_infra",
        "doc_afcom_density",
        "tech_cooling",
        "infrastructure_constraint",
        "Data-center rack density growth makes cooling readiness a facility-level constraint.",
        "Average rack density is rising and liquid cooling adoption is accelerating.",
        0.76,
        82,
    ),
    Claim(
        "claim_cooling_nvidia_counter",
        "doc_nvidia_blackwell_cooling",
        "tech_cooling",
        "counterargument",
        "Liquid-cooled system designs can improve water and energy efficiency compared with traditional approaches.",
        "NVIDIA presented liquid cooling as improving density, energy costs, and water efficiency.",
        0.78,
        45,
    ),
    Claim(
        "claim_hbm_micron_demand",
        "doc_micron_q2_2026",
        "tech_hbm",
        "demand_signal",
        "AI server growth is constrained by inadequate memory supply.",
        "Micron said server demand is constrained by inadequate DRAM and NAND supply.",
        0.88,
        88,
    ),
    Claim(
        "claim_hbm_skhynix_demand",
        "doc_skhynix_outlook_2026",
        "tech_hbm",
        "demand_signal",
        "AI-specific memory demand with HBM at the center is expected to grow rapidly through 2028.",
        "SK hynix described rapid growth expectations for HBM-led AI memory.",
        0.84,
        84,
    ),
    Claim(
        "claim_hbm_tsmc_packaging",
        "doc_tsmc_cowos_2026",
        "tech_hbm",
        "capacity_signal",
        "HBM demand is linked to advanced packaging scale because AI systems need more memory in package.",
        "TSMC said CoWoS expansion supports more computing power and memory in a single package.",
        0.84,
        80,
    ),
    Claim(
        "claim_hbm_micron_counter",
        "doc_micron_hbm4_2026",
        "tech_hbm",
        "counterargument",
        "Micron HBM4 volume shipments show suppliers are adding capacity for next-generation platforms.",
        "Micron announced HBM4 volume shipments designed for NVIDIA Vera Rubin.",
        0.82,
        46,
    ),
    Claim(
        "claim_cowos_tsmc_capacity",
        "doc_tsmc_cowos_2026",
        "tech_cowos",
        "capacity_signal",
        "TSMC is expanding CoWoS capacity to support AI demand for more compute and memory in one package.",
        "TSMC said CoWoS expansion supports more computing power and memory in a single package.",
        0.84,
        82,
    ),
    Claim(
        "claim_networking_arista_demand",
        "doc_arista_ai_networking",
        "tech_networking",
        "demand_signal",
        "AI clusters with more than 100,000 accelerator nodes create new network design challenges.",
        "Arista described 100,000-node Ethernet AI clusters and scale-related design challenges.",
        0.82,
        82,
    ),
    Claim(
        "claim_networking_nvidia_technical",
        "doc_nvidia_spectrumx",
        "tech_networking",
        "technical_constraint",
        "Scaling AI fabrics within and across data centers requires purpose-built networking and telemetry.",
        "NVIDIA presents Spectrum-X for scaling AI networking within and across data centers.",
        0.84,
        80,
    ),
    Claim(
        "claim_networking_arista_infra",
        "doc_arista_ai_networking",
        "tech_networking",
        "infrastructure_constraint",
        "Large AI clusters create physical space and power-consumption constraints in the network layer.",
        "Arista noted physical space and power-consumption needs at large cluster scale.",
        0.8,
        78,
    ),
    Claim(
        "claim_networking_broadcom_counter",
        "doc_broadcom_ai_networking",
        "tech_networking",
        "counterargument",
        "Open Ethernet ecosystems and new switch platforms can reduce networking bottleneck severity over time.",
        "Broadcom described open, scalable, power-efficient AI networking platforms.",
        0.78,
        50,
    ),
    Claim(
        "claim_switch_asic_broadcom_capacity",
        "doc_broadcom_ai_networking",
        "tech_switch_asic",
        "capacity_signal",
        "Broadcom's Tomahawk and Jericho switch silicon are central to scaling AI networking platforms.",
        "Broadcom described Tomahawk, Jericho, and CPO switching as an open, scalable, power-efficient AI networking platform.",
        0.82,
        80,
    ),
    Claim(
        "claim_switch_asic_nvidia_demand",
        "doc_nvidia_spectrumx",
        "tech_switch_asic",
        "demand_signal",
        "Purpose-built switch platforms are required as AI networking scales within and across data centers.",
        "NVIDIA presents Spectrum-X as an AI networking platform for scaling within and across data centers.",
        0.82,
        78,
    ),
    Claim(
        "claim_optical_transceiver_lumentum_capacity",
        "doc_lumentum_pluggables",
        "tech_optical_transceiver",
        "capacity_signal",
        "800G and 1.6T optical modules are part of the scaling path for AI data-center connectivity.",
        "Lumentum describes scalable optical technologies including 800G and 1.6T modules.",
        0.78,
        76,
    ),
    Claim(
        "claim_optical_transceiver_coherent_capacity",
        "doc_coherent_cpo_lasers",
        "tech_optical_transceiver",
        "capacity_signal",
        "High-power laser supply supports silicon photonic transceivers used in AI data-center optical links.",
        "Coherent said it is producing high-power lasers in volume for silicon photonic transceivers.",
        0.78,
        74,
    ),
    Claim(
        "claim_cpo_broadcom_technical",
        "doc_broadcom_cpo_reliability",
        "tech_cpo",
        "technical_constraint",
        "CPO is being adopted to reduce optical power and improve link reliability in AI networks.",
        "Broadcom reported CPO reduces optics power versus pluggable approaches.",
        0.84,
        84,
    ),
    Claim(
        "claim_cpo_nvidia_demand",
        "doc_nvidia_cpo",
        "tech_cpo",
        "demand_signal",
        "AI factory scale is pulling co-packaged optics into 2026 switch roadmaps.",
        "NVIDIA described CPO availability planned across 2026 switch platforms.",
        0.86,
        82,
    ),
    Claim(
        "claim_cpo_coherent_capacity",
        "doc_coherent_cpo_lasers",
        "tech_cpo",
        "capacity_signal",
        "CPO depends on photonics component supply, including high-power lasers for silicon photonics.",
        "Coherent said it is producing high-power lasers for silicon photonic transceivers and CPO.",
        0.8,
        78,
    ),
    Claim(
        "claim_cpo_lumentum_counter",
        "doc_lumentum_pluggables",
        "tech_cpo",
        "counterargument",
        "Pluggable 800G and 1.6T optical modules can extend the life of non-CPO architectures.",
        "Lumentum describes scalable 800G and 1.6T modules plus future CPO light-source modules.",
        0.76,
        48,
    ),
    Claim(
        "claim_rack_density_nvidia_demand",
        "doc_nvidia_blackwell_cooling",
        "tech_rack_density",
        "demand_signal",
        "Rack-scale AI systems are increasing rack density and changing facility requirements.",
        "NVIDIA presented GB200 NVL72 as a rack-scale liquid-cooled system designed for high compute density.",
        0.84,
        84,
    ),
    Claim(
        "claim_rack_density_afcom_infra",
        "doc_afcom_density",
        "tech_rack_density",
        "infrastructure_constraint",
        "Rising rack density is becoming a facility-level deployment constraint for AI data centers.",
        "AFCOM described average rack density rising and liquid cooling adoption accelerating.",
        0.76,
        82,
    ),
]
